#!/bin/bash

fail() { echo "failed"; exit 1; }
trap fail ERR INT TERM

if [[ $# -ne 1 ]]
then
    echo "usage: $0 <script>"
    exit 1
fi

SCRIPT=$1
REGION=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r '.region')

cat <<EOT
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
EOT

FIRST=1
grep "aws ec2" $SCRIPT | sed "s/aws ec2/|/g" | cut -d'|' -f2 | 
awk '{print $1}' | sort -u |
while read COMMAND
do
    test $FIRST -eq 0 && echo ","
    FIRST_WORD=$(echo $COMMAND | cut -f 1 -d '-')
    SECOND_WORD=$(echo $COMMAND | cut -f 2 -d '-')
    echo -n "                \"ec2:${FIRST_WORD^}${SECOND_WORD^}\""
    FIRST=0
done
echo

cat <<EOT
            ],
            "Resource": "*",
            "Condition": {
                "StringEquals": {
                    "ec2:Region": "$REGION"
                }
            }
        }
    ]
}
EOT

